name: reddit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.6.5
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ 
    - assets/images/
